// Autores: Julieta Lopez (295568) y Joaquin Borges (284675)
package Interfaz;

import javax.swing.table.DefaultTableModel;
import Dominio.Puesto;
import Dominio.Sistema;
import java.util.ArrayList;

public class VentanaConsultaPuestos extends javax.swing.JFrame {

private Sistema sistema;

    public VentanaConsultaPuestos(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        rellenarTablaPuestos();
    }
    
    private void rellenarTablaPuestos() {
        ArrayList<Puesto> puestos = sistema.getListaPuesto();
        
//        Collections.sort(puestos, new Comparator<Puesto>() {
//            @Override
//            public int compare(Puesto p1, Puesto p2) {
//                int id1 = Integer.parseInt(p1.getId());
//                int id2 = Integer.parseInt(p2.getId());
//                return Integer.compare(id1, id2);
//            }
//        });
        
        // Definir el nombre de las columnas
        String[] nombresColumnas = {"ID", "Dueño", "Ubicación", "Empleados"};
        
        // Crear array de datos
        Object[][] data = new Object[puestos.size()][nombresColumnas.length];
        for (int i = 0; i < puestos.size(); i++) {
            data[i][0] = puestos.get(i).getId();
            data[i][1] = puestos.get(i).getDueño();
            data[i][2] = puestos.get(i).getUbicacion();
            data[i][3] = puestos.get(i).getCantE();
        }
        
        // Crear modelo tabla
        DefaultTableModel model = new DefaultTableModel(data, nombresColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evitar que se puedan evitar las celdas
            }
        };
        
        // Set del modelo a la tabla
        jTablePuestos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePuestos = new javax.swing.JScrollPane();
        jTablePuestos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePuestos.setViewportView(jTablePuestos);

        getContentPane().add(jScrollPanePuestos);
        jScrollPanePuestos.setBounds(40, 20, 375, 402);

        setBounds(0, 0, 550, 455);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        Sistema sistema = new Sistema();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaPuestos(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPanePuestos;
    private javax.swing.JTable jTablePuestos;
    // End of variables declaration//GEN-END:variables
}
