package Interfaz;

import Dominio.Mayorista;
import Dominio.Producto;
import Dominio.Sistema;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

public class VentanaConsultaMayoristas extends javax.swing.JFrame {
    
    private Sistema sistema;

    public VentanaConsultaMayoristas(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        rellenarTablaMayoristas();
    }
    
    private void rellenarTablaMayoristas() {
        ArrayList<Mayorista> mayoristas = sistema.getListaMayorista();

        // Definir nombre de las columnas
        String[] nombresColumnas = {"RUT", "Nombre", "Dirección", "Productos"};

        // Crear array de datos
        Object[][] data = new Object[mayoristas.size()][nombresColumnas.length];
        for (int i = 0; i < mayoristas.size(); i++) {
            Mayorista mayorista = mayoristas.get(i);
            ArrayList<Producto> productos = mayorista.getProducto();

            // Ordenar los productos por nombre
            Collections.sort(productos, Comparator.comparing(Producto::getNombre));

            StringBuilder productosNombres = new StringBuilder();
            for (Producto p : productos) {
                productosNombres.append(p.getNombre()).append(", ");
            }

            data[i][0] = mayorista.getRut();
            data[i][1] = mayorista.getNombre();
            data[i][2] = mayorista.getDire();
            data[i][3] = productosNombres.length() > 0 ? productosNombres.substring(0, productosNombres.length() - 2) : "";
        }

        // Create table model
        DefaultTableModel model = new DefaultTableModel(data, nombresColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evitar celdas editables
            }
        };

        // Set the model to the table
        jTableMayoristas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMayoristas = new javax.swing.JScrollPane();
        jTableMayoristas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableMayoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneMayoristas.setViewportView(jTableMayoristas);

        getContentPane().add(jScrollPaneMayoristas);
        jScrollPaneMayoristas.setBounds(30, 20, 375, 402);

        setBounds(0, 0, 525, 454);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaMayoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaMayoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaMayoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaMayoristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Sistema sistema = new Sistema();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaMayoristas(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneMayoristas;
    private javax.swing.JTable jTableMayoristas;
    // End of variables declaration//GEN-END:variables
}
