package Interfaz;

import Dominio.DueñoPuesto;
import Dominio.Sistema;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

public class VentanaConsultaDueño extends javax.swing.JFrame {

    private Sistema sistema;

    public VentanaConsultaDueño(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        rellenarTablaDuenos();
    }
    
    private void rellenarTablaDuenos() {
        ArrayList<DueñoPuesto> duenos = sistema.getListaDueños();
        
        // Ordenar los dueños por nombre
        Collections.sort(duenos, Comparator.comparing(DueñoPuesto::getNombre));
        
        // Definir el nombre de las columnas
        String[] nombresColumnas = {"Nombre", "Edad", "Experiencia"};
        
        // Crear array de datos
        Object[][] data = new Object[duenos.size()][nombresColumnas.length];
        for (int i = 0; i < duenos.size(); i++) {
            data[i][0] = duenos.get(i).getNombre();
            data[i][1] = duenos.get(i).getEdad();
            data[i][2] = duenos.get(i).getExperiencia();
        }
        
        // Crear modelo tabla
        DefaultTableModel model = new DefaultTableModel(data, nombresColumnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evitar que se puedan evitar las celdas
            }
        };
        
        // Set del modelo a la tabla
        jTableDuenos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneDuenos = new javax.swing.JScrollPane();
        jTableDuenos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableDuenos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneDuenos.setViewportView(jTableDuenos);

        getContentPane().add(jScrollPaneDuenos);
        jScrollPaneDuenos.setBounds(50, 20, 375, 402);

        setBounds(0, 0, 570, 446);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Sistema sistema = new Sistema();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaDueño(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneDuenos;
    private javax.swing.JTable jTableDuenos;
    // End of variables declaration//GEN-END:variables
}
